version: '3.4'
services:
  db:
    image: ptzaluar/mysql-spring-boot-udemy
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: dockerptz
      MYSQL_USER: dockerptz
      MYSQL_PASSWORD: dockerptz
      MYSQL_DATABASE: rest_spring_boot_udemy
    ports:
      - "3308:3306"
    networks:
      - udemy-network
  spring-boot-udemy:
    image: ptzaluar/spring-boot-udemy
    restart: always
    build: ./SpringBootUdemy
    working_dir: /SpringBootUdemy
    environment:
      TZ: America/Sao_Paulo
      SPRING_BOOT_ENVIRONMENT: Production
    volumes:
      - ./SpringBootUdemy:/SpringBootUdemy
      - ~/.m2:/root/.m2
    ports:
      - "8080:8080"
    command: mvn clean spring-boot:run
    links:
      - db
    depends_on:
      - db
    networks:
      - udemy-network
networks:
    udemy-network:
        driver: bridge